name: Build OpenSupaplex Release
on:
  push:
    tags:
      - v*
jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build OpenSupaplex for Ubuntu
      run: |
        ./linux/ci-prepare.sh
        ./linux/ci-build.sh
      shell: bash
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build OpenSupaplex for macOS
      run: |
        ./macos/ci-prepare.sh
        ./macos/ci-build.sh
      shell: bash
    - name: Upload macOS build
      uses: actions/upload-artifact@v1
      with:
        name: macos-build
        path: macos/OpenSupaplex-macOS.zip
  build-vita:
    runs-on: ubuntu-18.04
    container: sergiou87/vita-docker-open-supaplex:7.1
    steps:
    - uses: actions/checkout@v1
    - name: Build OpenSupaplex for PS Vita
      run: |
        ./vita/ci-build-vita.sh
      shell: bash
    - name: Upload PS Vita build
      uses: actions/upload-artifact@v1
      with:
        name: vita-build
        path: vita/build/OpenSupaplex.vpk
  build-switch:
    runs-on: ubuntu-18.04
    container: sergiou87/switch-docker-open-supaplex:7.1
    steps:
    - uses: actions/checkout@v1
    - name: Build OpenSupaplex for Nintendo Switch
      run: |
        ./switch/ci-build-switch.sh
      shell: bash
    - name: Upload Nintendo Switch build
      uses: actions/upload-artifact@v1
      with:
        name: switch-build
        path: switch/OpenSupaplex-switch.zip
  build-psp:
    runs-on: ubuntu-18.04
    container: sergiou87/pspdev-docker-open-supaplex:7.1
    steps:
    - uses: actions/checkout@v1
    - name: Build OpenSupaplex for PSP
      run: |
        ./psp/ci-install-dependencies.sh
        ./psp/ci-build.sh
      shell: bash
    - name: Upload PSP build
      uses: actions/upload-artifact@v1
      with:
        name: psp-build
        path: psp/OpenSupaplex-psp.zip
  build-ps3:
    runs-on: ubuntu-18.04
    container: sergiou87/ps3dev-docker-open-supaplex:7.1
    steps:
    - uses: actions/checkout@v1
    - name: Build OpenSupaplex for PS3
      run: |
        ./ps3/ci-build.sh
      shell: bash
    - name: Upload PS3 build
      uses: actions/upload-artifact@v1
      with:
        name: ps3-build
        path: ps3/OpenSupaplex.pkg
  build-wii:
    runs-on: ubuntu-18.04
    container: sergiou87/wii-docker-open-supaplex:7.1
    steps:
    - uses: actions/checkout@v1
    - name: Build OpenSupaplex for Wii
      run: |
        ./wii/ci-build.sh
      shell: bash
    - name: Upload Wii build
      uses: actions/upload-artifact@v1
      with:
        name: wii-build
        path: wii/OpenSupaplex-wii.zip
  build-wiiu:
    runs-on: ubuntu-18.04
    container: sergiou87/wiiu-docker-open-supaplex:7.1
    steps:
    - uses: actions/checkout@v1
    - name: Build OpenSupaplex for Wii U
      run: |
        ./wiiu/ci-build.sh
      shell: bash
    - name: Upload Wii Ubuild
      uses: actions/upload-artifact@v1
      with:
        name: wiiu-build
        path: wiiu/OpenSupaplex-wiiu.zip
  build-old-3ds:
    runs-on: ubuntu-18.04
    container: sergiou87/3ds-docker-open-supaplex:7.1
    steps:
    - uses: actions/checkout@v1
    - name: Build OpenSupaplex for Old Nintendo 3DS
      run: |
        ./3ds/ci-build-old-3ds.sh
      shell: bash
    - name: Upload Old Nintendo 3DS build
      uses: actions/upload-artifact@v1
      with:
        name: old-3ds-build
        path: 3ds/OpenSupaplex-old-3ds.zip
  build-new-3ds:
    runs-on: ubuntu-18.04
    container: sergiou87/3ds-docker-open-supaplex:7.1
    steps:
    - uses: actions/checkout@v1
    - name: Build OpenSupaplex for New Nintendo 3DS
      run: |
        ./3ds/ci-build-new-3ds.sh
      shell: bash
    - name: Upload New Nintendo 3DS build
      uses: actions/upload-artifact@v1
      with:
        name: new-3ds-build
        path: 3ds/OpenSupaplex-new-3ds.zip
  build-windows-x86_64:
    runs-on: windows-latest
    steps:
    - uses: numworks/setup-msys2@v1
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v1
    - name: Prepare build environment
      run: |
        msys2do ./windows/ci-prepare.sh x86_64
    - name: Build OpenSupaplex for Windows x86_64
      run: |
        cd windows
        msys2do ./ci-build.sh x86_64
    - name: Upload Windows x86_64 build
      uses: actions/upload-artifact@v1
      with:
        name: windows-x86_64-build
        path: windows/OpenSupaplex-windows-x86_64.zip
  create-release:
    needs: [ build-vita, build-macos, build-switch, build-old-3ds, build-new-3ds, build-windows-x86_64, build-psp, build-ps3, build-wii, build-wiiu ]
    runs-on: ubuntu-latest
    steps:
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - uses: actions/checkout@v1
    - id: read_release_notes
      run: |
        CONTENTS=`cat changelog/${{ steps.get_version.outputs.VERSION }}.txt`
        CONTENTS="${CONTENTS//'%'/'%25'}"
        CONTENTS="${CONTENTS//$'\n'/'%0A'}"
        CONTENTS="${CONTENTS//$'\r'/'%0D'}" 
        echo "::set-output name=release_notes::${CONTENTS}"
      shell: bash
    - name: Download macOS Build Asset
      uses: actions/download-artifact@v1
      with:
        name: macos-build
    - name: Download PS Vita Build Asset
      uses: actions/download-artifact@v1
      with:
        name: vita-build
    - name: Download Nintendo Switch Build Asset
      uses: actions/download-artifact@v1
      with:
        name: switch-build
    - name: Download PSP Build Asset
      uses: actions/download-artifact@v1
      with:
        name: psp-build
    - name: Download PS3 Build Asset
      uses: actions/download-artifact@v1
      with:
        name: ps3-build
    - name: Download Wii Build Asset
      uses: actions/download-artifact@v1
      with:
        name: wii-build
    - name: Download Wii U Build Asset
      uses: actions/download-artifact@v1
      with:
        name: wiiu-build
    - name: Download Old Nintendo 3DS Build Asset
      uses: actions/download-artifact@v1
      with:
        name: old-3ds-build
    - name: Download New Nintendo 3DS Build Asset
      uses: actions/download-artifact@v1
      with:
        name: new-3ds-build
    - name: Download Windows x86_64 Build Asset
      uses: actions/download-artifact@v1
      with:
        name: windows-x86_64-build
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: OpenSupaplex ${{ github.ref }}
        body: ${{ steps.read_release_notes.outputs.release_notes }}
        draft: false
        prerelease: false
    - name: Upload macOS Build Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: macos-build/OpenSupaplex-macOS.zip
        asset_name: OpenSupaplex-macOS-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/binary
    - name: Upload PS Vita Build Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: vita-build/OpenSupaplex.vpk
        asset_name: OpenSupaplex-vita-${{ steps.get_version.outputs.VERSION }}.vpk
        asset_content_type: application/binary
    - name: Upload Nintendo Switch Build Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: switch-build/OpenSupaplex-switch.zip
        asset_name: OpenSupaplex-switch-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip
    - name: Upload PSP Build Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: psp-build/OpenSupaplex-psp.zip
        asset_name: OpenSupaplex-psp-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip
    - name: Upload PS3 Build Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ps3-build/OpenSupaplex.pkg
        asset_name: OpenSupaplex-ps3-${{ steps.get_version.outputs.VERSION }}.pkg
        asset_content_type: application/binary
    - name: Upload Wii Build Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: wii-build/OpenSupaplex-wii.zip
        asset_name: OpenSupaplex-wii-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip
    - name: Upload Wii U Build Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: wiiu-build/OpenSupaplex-wiiu.zip
        asset_name: OpenSupaplex-wiiu-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip
    - name: Upload Old Nintendo 3DS Build Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: old-3ds-build/OpenSupaplex-old-3ds.zip
        asset_name: OpenSupaplex-old-3ds-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip
    - name: Upload New Nintendo 3DS Build Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: new-3ds-build/OpenSupaplex-new-3ds.zip
        asset_name: OpenSupaplex-new-3ds-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip
    - name: Upload Windows x86_64 Build Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: windows-x86_64-build/OpenSupaplex-windows-x86_64.zip
        asset_name: OpenSupaplex-windows-x86_64-${{ steps.get_version.outputs.VERSION }}.zip
        asset_content_type: application/zip
